apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2v6g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2v6g
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2v6g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2v6g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2v6g
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vxbo-tenant/rhtap-demo-app/hacbs-test-project-2v6g@sha256:1721f74f81bdc6206d05408c7bcfc4721e560c132aa01008f078b963bfa5f2c9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
